DROP FUNCTION IF EXISTS sp_get_firstday_of_nextmonth;
DELIMITER //
CREATE FUNCTION sp_get_firstday_of_nextmonth(
) RETURNS DATE
BEGIN
	RETURN (SELECT DATE_SUB(
						 LAST_DAY(DATE_ADD(NOW(), INTERVAL 1 MONTH))
						,INTERVAL DAY(LAST_DAY(DATE_ADD(NOW(), INTERVAL 1 MONTH))) -1 DAY
					));
END //
DELIMITER ;