<?php


namespace App;

use Illuminate\Database\Eloquent\Model;

class UserMod extends Model
{
    const MODULE_BINARY_TREE = "BINARY_TREE";

    protected $table = "users_mods";
    private $_done_by_user_id = null;
    private $_done_from_module = null;
    private $_changes = [];
    public $timestamps = false;

    public static function newRecordFor($user_id)
    {
        $o = new static();
        $o->ip = null;
        $o->userid = $user_id;

        return $o;
    }

    public function setDoneBy($user_id)
    {
        $this->_done_by_user_id = $user_id;
        return $this;
    }

    public function setFromModule($module)
    {
        if (strlen($module) > 13) {
            throw new \Exception("Module length exceeded");
        }

        $this->_done_from_module = $module;
        return $this;
    }

    public function setIP($ip)
    {
        $this->ip = $ip;
        return $this;
    }

    public function setChanges($column, $old_value, $new_value)
    {
        $this->_changes[] = "$column old: $old_value, new: $new_value";
        return $this;

    }

    public function save(array $options = [])
    {
        if($this->_done_by_user_id === null) {
            $this->_done_by_user_id = $this->userid;
        }

        $this->doneby = "$this->_done_by_user_id $this->_done_from_module";

        if($this->ip === null) {
            $this->ip = request()->ip();
        }

        $this->vals = implode($this->_changes, "<br>");

        return parent::save($options); // TODO: Change the autogenerated stub
    }
}